name: islamy
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  intl: ^0.19.0
  localization: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/files/

  fonts:
    - family: ElMessiri
      fonts:
        - asset: assets/fonts/ElMessiri-SemiBold.ttf

    - family: Flat
      fonts:
        - asset: assets/fonts/JF Flat regular.otf

    - family: DTHULUTH
      fonts:
        - asset: assets/fonts/DTHULUTH.TTF

    - family: KOUFIBD
      fonts:
        - asset: assets/fonts/KOUFIBD.TTF
